# Basic Python

## 1. Split this string

In [29]:
s = "Hi there Sam!"

In [6]:
In [4]
s = 'Hi there Sam!'
In [4]
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [11]:
planet = "Earth"
diameter = 12742

In [12]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [13]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [14]:
d2 = d['k1'][3]
d3 = d2['tricky'][3]
print(d3['target'][3])

hello


# Numpy

In [15]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [16]:
import numpy as np
array=np.zeros(10)
print("array of 10 zeros:")
print(array)

array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
array=np.ones(10)*5
print("array of 10 fives:")
print(array)

array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [18]:
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b),axis=None)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [23]:
import pandas as pd
data = [['tom',10],['nick',15],['juli',14]]
df = pd.DataFrame(data,columns=['Name','Age'])
df


Name  Age
0   tom   10
1  nick   15
2  juli   14

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
per1 = pd.date_range(start ='1-1-2023',end='2-10-2023',freq='14H')
for val in per1:
  print(val)

2023-01-01 00:00:00
2023-01-01 14:00:00
2023-01-02 04:00:00
2023-01-02 18:00:00
2023-01-03 08:00:00
2023-01-03 22:00:00
2023-01-04 12:00:00
2023-01-05 02:00:00
2023-01-05 16:00:00
2023-01-06 06:00:00
2023-01-06 20:00:00
2023-01-07 10:00:00
2023-01-08 00:00:00
2023-01-08 14:00:00
2023-01-09 04:00:00
2023-01-09 18:00:00
2023-01-10 08:00:00
2023-01-10 22:00:00
2023-01-11 12:00:00
2023-01-12 02:00:00
2023-01-12 16:00:00
2023-01-13 06:00:00
2023-01-13 20:00:00
2023-01-14 10:00:00
2023-01-15 00:00:00
2023-01-15 14:00:00
2023-01-16 04:00:00
2023-01-16 18:00:00
2023-01-17 08:00:00
2023-01-17 22:00:00
2023-01-18 12:00:00
2023-01-19 02:00:00
2023-01-19 16:00:00
2023-01-20 06:00:00
2023-01-20 20:00:00
2023-01-21 10:00:00
2023-01-22 00:00:00
2023-01-22 14:00:00
2023-01-23 04:00:00
2023-01-23 18:00:00
2023-01-24 08:00:00
2023-01-24 22:00:00
2023-01-25 12:00:00
2023-01-26 02:00:00
2023-01-26 16:00:00
2023-01-27 06:00:00
2023-01-27 20:00:00
2023-01-28 10:00:00
2023-01-29 00:00:00
2023-01-29 14:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [27]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [28]:
import pandas as pd
lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df = pd.DataFrame(lists,columns =['sno','name','rno'])
print(df)

   sno name  rno
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
